name: Azure Infrastructure Deployment with Terraform

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # Runs on an Ubuntu virtual machine

    steps:
      # Step 1: Checkout the repository to get the Terraform files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform (this sets up the correct Terraform version)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.0'  # Set the required Terraform version

      # Step 3: Log in to Azure using Service Principal credentials
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Azure credentials stored in GitHub secrets

      # Step 4: Initialize Terraform (downloads provider plugins, etc.)
      - name: Terraform Init
        run: terraform init

      # Step 5: Run Terraform Plan (to preview changes before applying)
      - name: Terraform Plan
        run: terraform plan
