name: 'Terraform root module azure resource'

on:
  push:
    branches:
      - none
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:  # ✅ Correct placement of environment variables
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.11
        
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform  # ✅ Ensure the working directory is set

    - name: Terraform Plan
      run: terraform plan -var-file=terraform.tfvars  # ✅ Removed redundant `-var` values (handled by env vars)
      working-directory: ./terraform
